version: '3.5'

services:
  redis:
    image: redis:latest
    networks:
      - internal_net
    volumes:
      - './redis_conf/redis.conf:/usr/local/etc/redis/redis.conf:ro'
      - 'redis_data:/data'
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - internal_net
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
      - './postgres_conf/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql:ro'
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - internal_net
    ports:
      - '8080:80'
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - internal_net
    ports:
      - '8090:80'
    depends_on:
      - redis
      - postgres
    restart: always

volumes:
  redis_data: null
  postgresql_data: null

networks:
  internal_net:
    driver: bridge
